= pipe2egg

(TODO logo)

A command-line pomodoro timer that's designed to be integrated into your status bar.

(TODO demo video)

== Usage

.In a terminal window
----
pomodoro
----

And the pomodoro application will start listening to messages on the named pipe `/tmp/pipe2egg.sock`.
The messages you can send are documented in the <<states-and-messages,States & Messages>> section

.In a different terminal window
----
echo 'play' >> /tmp/pipe2egg.sock
----

[[states-and-messages]]
=== States & Messages

.Usage flowchart
----

               +-------+
               | IDLE  +<----------------------+
               +---+---+                       |
                   |                           |
                   |play                       |
                   v                           |
             +-----+-----+                     |
             |  SETTING  +<-------+            |
             +----+--+---+        |            |
                  |  |            |            |
                  |  |   next     |            |
              play|  +------------+            |
                  |                            |
                  |                            |
                  v                            |
      play    +---+----+                       |
+-------------+  WORK  +<-----------+          |
|             +---+----+            |          |
|                 |                 |          |
|            (time over)            |play      |
|                 |                 |          |
|                 v                 |          |
|          +------+-------   +------+------+   |
|          |  WAIT REST  |   | WAIT WORK   |   |
|          +------+-------   +------+------+   |
|                 |                 ^          |
|                 |play             |          |
|                 |                 |          |
|                 v                 |          |
|     play    +---+----+            |          |
+<------------+  REST  |            |          |
|             +---+----+            |          |
|                 |                 |no        |
|            (time over)            |          |
|                 |                 |          |
|                 v                 |          |
|        +------------------+       |          |
|      +----------------------+     |          |
|      | | repated 3 times  | +-----+          |
|      +----------------------+                |
|        +------------------+                  |
|                 |                            |
|                 |yes                         |
|                 |                            |
|                 v                            |
|          +------+-----+                      |
+--------> |  FINISHED  +----------------------+
           +------------+




     +---------+
     |  STATE  |
     +---------+

     +---------+  action   +---------+
     |  STATE  +---------->+  STATE  |
     +---------+           +---------+

     +---------+  (event)  +---------+
     |  STATE  +---------->+  STATE  |
     +---------+           +---------+

       +------------------+  
     +----------------------+
     | |    condition     | |
     +----------------------+
       +------------------+  

----

- IDLE (`IDL`)
- SETTING (`W/R/L`) : "Work for W minutes, Rest for R minutes" repeated 3 times. Last rest session is L minutes long
- WORK `W x`: x minutes of work left
- REST `R x`: x minutes of rest left
- WAIT WORK `w x`: waiting to start x minutes of work
- WAIT REST `r x`: waiting to start x minutes of rest
- FINISHED `FIN`: pomodoro session finished

== Install

1. clone git repo
2. make
3. make install #or make PREFIX=... install
